name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx6G -Xss4M -XX:+UseG1GC # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx6G -Xss4M -XX:+UseG1GC # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)
  NODE_OPTIONS: --max_old_space_size=6144

on:
  # pull_request:
  # push:
  #   branches: ['main']
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    needs: [build]
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - run: sbt ci-release
        env:
          # PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.GPG_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          